services:
  postgres:
    image: postgres:16-alpine
    container_name: orcamento-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orcamento
    ports:
      - "5435:5432"
    volumes:
      - orcamento_pg_data:/var/lib/postgresql/data

volumes:
  orcamento_pg_data:
